name: sellermultivendor
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.1+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_svg: ^1.1.0
  http: ^0.13.4
  jaguar_jwt: ^3.0.0
  shared_preferences: ^2.0.11
  connectivity_plus: ^2.3.1
  firebase_auth: ^3.3.4
  cached_network_image: ^3.2.1
  firebase_core: ^1.10.6
  country_code_picker: ^2.0.2
  intl: ^0.17.0 
  flutter_localizations:
    sdk: flutter
  shimmer: ^2.0.0
  url_launcher: ^6.0.17
  sms_autofill: ^2.2.0
  image_picker: ^0.8.4+4
  fl_chart: ^0.51.0 
  file_picker: ^4.3.0 
  flutter_local_notifications: ^9.5.3+1
  firebase_messaging: ^11.2.4
  sticky_headers: ^0.3.0+2
  # flutter_html: ^2.2.1
  html_editor_enhanced: ^2.4.0+1
  mime: ^1.0.1
  lottie: ^1.2.1
  flutter_rating_bar: ^4.0.0
  photo_view: ^0.14.0
  flutter_widget_from_html: ^0.8.5
  provider: ^6.0.3
  fwfh_text_style: ^2.22.08+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - lib/Language/

  fonts:
    - family: opensans
      fonts:
         - asset: assets/font/OpenSans-Regular.ttf
